### ISSUE TITLE
Plugin usage documentation tracking

### ISSUE THREAD

**Issue by alecgeatches** [Automattic/vip-block-data-api#12]
Closed original PR https://github.com/Automattic/vip-content-api/pull/9 in favor of merging README changes into `trunk` so that documentation progress is more easily viewable. I'll be using this issue to track the remaining changes:

- [x] Document `vip_content_api__sourced_block_result` filter usage for custom block attributes
- [x] Document permissions filters: `vip_content_api__rest_validate_post_id` / `vip_content_api__rest_permission_callback`
- [x] Provide examples of Gutenberg blocks and Content API output
- [x] Installation instructions + release link
- [x] Document client-side block support with delimiter attributes
- [x] Add basic usage instructions
- [x] Explain limitations with deprecated block structures
- [x] Document the rich text limitation and how we may address it in the future
- [x] Document warnings and error responses
- [x] VIP caching for REST API
- [x] Add vanilla React example using content API

**Comment by alecgeatches** [comment]
Finished the documentation tasks for the initial closed beta release of the plugin! Closing this issue.
